export default [
      {text: "P-1 Preservation - Restricted", value: "P-1"},
      {text: "F-1 Preservation - Military and Federal", value: "F-1"},
      {text: "P-2 Preservation - General", value: "P-2"},
      {text: "AG-1 Agricultural - Restricted", value: "AG-1"},
      {text: "AG-2 Agricultural - General", value: "AG-2"},
      {text: "C Country", value: "C"},
      {text: "R-20 Residential", value: "R-20"},
      {text: "R-10 Residential", value: "R-10"},
      {text: "R-7.5 Residential", value: "R-7.5"},
      {text: "R-5 Residential", value: "R-5"},
      {text: "R-3.5 Residential", value: "R-3.5"},
      {text: "A-1 Apartment - Low-density", value: "A-1"},
      {text: "A-2 Apartment - Medium-density", value: "A-2"},
      {text: "A-3 Apartment - High-density", value: "A-3"},
      {text: "AMX-1 Apartment Mixed-Use - Low-density", value: "AMX-1"},
      {text: "AMX-2 Apartment Mixed-Use - Medium-density", value: "AMX-2"},
      {text: "AMX-3 Apartment Mixed-Use - High-density", value: "AMX-3"},
      {text: "Resort Resort", value: "Resort"},
      {text: "B-1 Business - Neighborhood", value: "B-1"},
      {text: "B-2 Business - Community", value: "B-2"},
      {text: "BMX-3 Business Mixed-use - Community", value: "BMX-3"},
      {text: "BMX-4 Business Mixed-use - Central", value: "BMX-4"},
      {text: "I-1 Industrial - Limited", value: "I-1"},
      {text: "I-2 Industrial - Intensive", value: "I-2"},
      {text: "I-3 Industrial - Waterfront", value: "I-3"},
      {text: "IMX-1 Industrial-Commercial Mixed Use", value: "IMX-1"}

]
